#!/bin/bash

echoerr() { echo "$@" 1>&2; }

#check if file exists
if [ ! -f /bbx/input/assembler.yaml ]
then
    printf 'No input data found at: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
fi

#validate yaml
python /bbx/bin/schema_validator.py -i /bbx/input/assembler.yaml -s /bbx/schema/schema.yaml

#if valid yaml run ray command
if [ $? -eq  0 ]
then	
	python /bbx/bin/command_handler.py -i /bbx/input/assembler.yaml -o /bbx/output
fi
